# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html

security:
    # ...


security:
    providers:
        in_memory:
            memory:
                users:
                    responsable :
                        password: responsable
                        roles: 'ROLE_RESPONSABLE'
                    admin:
                        password: kitten
                        roles: 'ROLE_ADMIN'
                    magasinier:
                        password: magasin
                        roles: 'ROLE_MAGASIN'
    encoders:
            Symfony\Component\Security\Core\User\User: plaintext
    firewalls:
            main:
                logout:
                    path:   /logout
                    target: /
                    invalidate_session: false
                anonymous: ~
                form_login:
                    login_path: login
                    check_path: login
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [ROLE_ADMIN , ROLE_RESPONSABLE, ROLE_MAGASIN]}
        - { path: ^/produit/new, roles: [ROLE_ADMIN , ROLE_RESPONSABLE]}

            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~
